server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
    gzip_min_length 1000;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, must-revalidate";
        add_header X-Content-Type-Options nosniff;
    }

    # Fichiers statiques — désactiver le cache pour les assets JS/CSS (dev)
    location ~* \.(js|css|geojson|json)$ {
        add_header Cache-Control "no-cache, must-revalidate";
        add_header Access-Control-Allow-Origin *;
    }
}
